### ISSUE TITLE
RiakBucket creation *still* not free of race conditions [JIRA: CLIENTS-439]

### ISSUE THREAD

**Issue by Tinche** [basho/riak-python-client#405] opened 2015-06-17 21:34 UTC
We see None being returned from RiakClient.bucket(..) a few dozen times per day on our worker processes. This is probably exacerbated by the fact we're forcing garbage collection in another thread periodically.

This has been tackled in https://github.com/basho/riak-python-client/commit/f944a8b6174bf17e2c57caa386bd199944a1f6c8 by using WeakValueDictionary.setdefault, but until http://bugs.python.org/issue19542 is merged in (status still open), setdefault isn't atomic itself, hence a race condition returning None is possible.

**Comment by javajolt** [comment] 2015-06-17 23:21
Thanks for reporting this, @Tinche.   I was going to say, I thought we already addressed this.   Looks like another solution might need to be crafted in the mean time.

**Comment by ovaltzer** [comment] 2017-02-23 09:56
Hey,
Just facing the very same issue here. we are using riak client for python (2.7.0).
Does instantiating the client per thread should be good enough to solve this issue for sure ? was it tested ? 
We tried that and almost sure that this problem was recreated even though we have a new client for each thread.

Thanks for the help.
Oded Valtzer

**Comment by lukebakken** [comment] 2017-02-23 16:31
Would it be possible to provide code that reproduces this reliably? Thanks.

**Comment by ovaltzer** [comment] 2017-02-23 16:52
Hey,
It's a very basic command, while running in python multi threaded envrionment.
The code that fails is this:

```
def save(self, key, value):
        try:
            ro = self.bucket.new(key)
            ro.data = value
            ro.store()
        except Exception as e:
            raise RiakInterfaceException(
                "Failed storing [key {}] to [bucket={}] riak. error:{}".format(key, self.bucket_name, e))
```

with RiakException:
```
error:'NoneType' object has no attribute 'new'
```

This save function is part of an internal wrapping of a riak bucket object. we create the bucket object at the moment before we use the save method, so the bucket object is not 'hanging' for a while.
moreover, we create a riak client object for each thread we open.
This code works in most of the times, bu somethimes, on different buckets, we get this errors. highly unexpected and only reproduced in multi threaded environment. Is the RiakClient python library use any global unsafe objects? 
Do we need to maybe close someway the riak client before the thread terminates ?

Thanks,
Oded

**Comment by lukebakken** [comment] 2017-02-23 17:10
> running in python multi threaded envrionment

Can you describe this more? Are you using the `threading` module? Which version of Python are you using?

>  we create a riak client object for each thread we open

The `RiakClient` object is thread safe, so only one instance is necessary. You must have a new `RiakClient` for each operating system process, of course.

> Is the RiakClient python library use any global unsafe objects?

It does not.

**Comment by ovaltzer** [comment] 2017-02-23 18:12
We started with a global riak client object and we encountered these problem and found out about this issue above which precisely says that there issues with multi threading.
We are using standard python  Thread Pool on top of the `tornado` event loop.
the version of python we use is 2.7.

Thanks for the quick responses

**Comment by ovaltzer** [comment] 2017-02-23 20:11
If we use multi get during our usage of the riak client, do we must close the riak client in an appripriate way ? i.e `riack_client.close()` as written in an earlier release notes?
```
Calling close on client closes pools, remove global multi pools. NOTE: if you use the multi get or put features of the client, you MUST call close() on your RiakClient instance to correctly clean up the thread pools used for these multi-operations.
```

**Comment by lukebakken** [comment] 2017-02-23 20:12
> If we use multi get during our usage of the riak client, do we must close the riak client in an appropriate way ? i.e riack_client.close() as written in an earlier release notes?

Yes. Note that is not the cause of this issue. This issue is due to bugs in Python and its libraries.

If you have time, I'll re-state that the fastest way to get a fix is to provide a 100% complete set of code that reproduces this issue.

I do not have time to work on this untill next week at the earliest.

**Comment by ovaltzer** [comment] 2017-02-24 19:13
I don't mind spending some time and writing simple multi thread code that generates this, but only if you really plan to work on it- as I understand this is an open issue planned to version 3 , that's why it feels awkward to me to write this example, as the issue is known and obvious. 

Thanks,
Oded

**Comment by alexmoore** [comment] 2017-02-25 03:06
Hi Oded,

Thanks again for finding a way to recreate this pesky persistent bug.  As Luke said, if we have a complete code example that reproduces the issue it will help us greatly and speed up the process.  Since it is a bug in Python, it may or may not have a straightforward fix. 

We can try our best to schedule some time to get this in soon, but we do have other obligations with upcoming releases and the other clients & libraries.  We could likely get it in soon if we had the reproducer, and it's not something that requires a patch to Python itself.

Thanks,
Alex Moore
Team Lead, Clients

**Comment by Tinche** [comment] 2017-02-25 18:26
Note that http://bugs.python.org/issue19542 has been fixed upstream. (https://github.com/python/cpython/commit/d4580ecb8da130fd9061565defcdb73bc08aa311)

**Comment by ovaltzer** [comment] 2017-02-27 07:36
@lukebakken @alexmoore 
Hey guys, it took a while but I managed to recreate the bug. please understand that this issue is a multi-thread issue that might not always happen, you might need to play with the amount of threads in your local env. to me it happens every time with 20 threads open.
again -  i use python 2.7, latest riak python client, latest riak-kv docker image, installed locally with one node (just for dev env). I also use YZ search enabled if it has any meaning for you guys.
Please let me know ASAP on your progress if there is any.
Thanks again for you quick responses and help.
```
from riak import RiakClient
from threading import Thread
import time
from string import ascii_lowercase
RIAK_HOST = "127.0.1.1"
THREADS_AMOUNT = 20


def bucket_worker(j):
    time.sleep(1)
    rc = RiakClient(host=RIAK_HOST)
    for n in range(1000):
        for char in ascii_lowercase:
            b = rc.bucket_type("sync").bucket(char)
            o = b.new(str(j))
            o.data = j
            o.store()
    rc.close()


threads = []

for i in range(THREADS_AMOUNT):
    t = Thread(target=bucket_worker, args=(i,))
    threads.append(t)
    t.start()
for t in threads:
    t.join()
```

**Comment by ovaltzer** [comment] 2017-02-27 11:58
Hey, 
after more testing, we found out that we use python 2.7.6 on ubuntu 14.04 (while the latest version is 2.7.13), but we are not sure if this is the reason for that, might worth checking it out also.

Oded

**Comment by lukebakken** [comment] 2017-02-27 18:27
@ovaltzer thank you for the code. I ran it using several versions of Python, first with `20` threads then `50`, decreasing the initial sleep to `0.1` seconds. Here are the results:

Verson | Reproduced?
----------|-------------------
`3.7.0-alpha1` | No
`3.6.0` | Yes
`3.5.3` | No
`3.5.2` | No
`2.7.13` | No
`2.7.6` | No

The issue is very dependent on your environment. According to the `cpython` logs for commits concerning [issue `19542`](http://bugs.python.org/issue19542) it *should* be fixed in `3.6.0` yet that is the one version that I could reliably reproduce the issue.

I'll see what I can do to work around this.

**Comment by ovaltzer** [comment] 2017-02-27 18:44
I managed to reproduce this 100% (using the exact parameters I sent in the code) of the times I run it with 2.7.6. but when running 2.7.13 did not(I'm not positive but I think that this issue also fixed in 2.7.13) .
Sometimes it takes some time until it reproduced (as the script is running for quite a while).

**Comment by lukebakken** [comment] 2017-02-27 18:56
Like I said, reproducing appears to be dependent on your environment. For instance, I just did a run of your test code with `3.6.0`, `50` threads, and did not see the issue at all.

Based on the [`cpython commit history`](https://github.com/python/cpython/search?q=19542&type=Commits) , there are three commits with the fix for [issue `#19542`](http://bugs.python.org/issue19542):

Commit | Tag / Branch
-----------|------------------------------------------------------
`ec60edb977dd14640a5bc95f00cccc214518971e` | `master`
`d4580ecb8da130fd9061565defcdb73bc08aa311` | `master`
`c1ee488962f0a20c2814b14a4c29d6082dd38add` | `v3.5.3`, `v3.5.3rc1`, `master`

I may be searching the commit history incorrectly, but it appears that this fix isn't in any release other than `3.5.3`. I will follow up on that.

**Comment by ovaltzer** [comment] 2017-02-27 19:10
Also, when running with large number of threads I couldn't reproduce that. It made my laptop run slower so probably the racing was not so meaningful...20 did the work

**Comment by lukebakken** [comment] 2017-02-27 19:22
@ovaltzer - it appears to be easier for you to reproduce this issue. Could you please run your test code using Python `3.5.3` and see if you run into the issue? I have attached an updated version of your code that works on Python 2 and 3.

[main.py.txt](https://github.com/basho/riak-python-client/files/804777/main.py.txt)

**Comment by lukebakken** [comment] 2017-02-27 21:04
@ovaltzer I opened PR #523 with a workaround for the bug in the Python `weakref` code. Basically, it re-tries the operation with an incrementing sleep value. It is far from ideal but refactoring the client to *not* use `WeakValueDictionary` isn't an option at this point.

Note that I could *never* reliably reproduce this issue on my workstation, so I can't be 100% sure that my change fixes the issue for good. If you could verify that the issue is resolved in your environment, I would appreciate it.

**Comment by ovaltzer** [comment] 2017-02-27 22:41
Thank you so much . I will check this tomorrow and let you know. Thanks for the very quick handling if this issue, its highly appreciated.

Oded

**Comment by lukebakken** [comment] 2017-03-07 16:37
@ovaltzer - did you get a chance to try the code in PR #523?

**Closed** 2017-03-27 23:03 UTC
Labels: JIRA: To Do
